/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArticlesArticle_category_1Example_1RouteImport } from './routes/articles/article_category_1/example_1'
import { Route as ArticlesArticle_category_2Example_2RouteImport } from './routes/articles/article_category_2/example_2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticle_category_1Example_1Route =
  ArticlesArticle_category_1Example_1RouteImport.update({
    id: '/articles/article_category_1/example_1',
    path: '/articles/article_category_1/example_1',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesArticle_category_2Example_2Route =
  ArticlesArticle_category_2Example_2RouteImport.update({
    id: '/articles/article_category_2/example_2',
    path: '/articles/article_category_2/example_2',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/article_category_1/example_1': typeof ArticlesArticle_category_1Example_1Route
  '/articles/article_category_2/example_2': typeof ArticlesArticle_category_2Example_2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/article_category_1/example_1': typeof ArticlesArticle_category_1Example_1Route
  '/articles/article_category_2/example_2': typeof ArticlesArticle_category_2Example_2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/article_category_1/example_1': typeof ArticlesArticle_category_1Example_1Route
  '/articles/article_category_2/example_2': typeof ArticlesArticle_category_2Example_2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles/article_category_1/example_1'
    | '/articles/article_category_2/example_2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles/article_category_1/example_1'
    | '/articles/article_category_2/example_2'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles/article_category_1/example_1'
    | '/articles/article_category_2/example_2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesArticle_category_1Example_1Route: typeof ArticlesArticle_category_1Example_1Route
  ArticlesArticle_category_2Example_2Route: typeof ArticlesArticle_category_2Example_2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/article_category_1/example_1': {
      id: '/articles/article_category_1/example_1'
      path: '/articles/article_category_1/example_1'
      fullPath: '/articles/article_category_1/example_1'
      preLoaderRoute: typeof ArticlesArticle_category_1Example_1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/article_category_2/example_2': {
      id: '/articles/article_category_2/example_2'
      path: '/articles/article_category_2/example_2'
      fullPath: '/articles/article_category_2/example_2'
      preLoaderRoute: typeof ArticlesArticle_category_2Example_2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesArticle_category_1Example_1Route:
    ArticlesArticle_category_1Example_1Route,
  ArticlesArticle_category_2Example_2Route:
    ArticlesArticle_category_2Example_2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
